Empty                  =
Space                  = $(Empty) $(Empty)
temproot			   = $(subst /Source,$(Space),$(CURDIR))
DEV_ROOT			   = $(word 1,$(temproot))

Source 				   = \
						ProjectData.c \
						Overall.c \



include $(MAKEFILEDIR)/gtken
include $(DEV_ROOT)/Makefile
